/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { JsonFilter } from "../../util/JsonFilter";
import { Type } from "class-transformer";
import { IsOptional, ValidateNested } from "class-validator";
import { StringFilter } from "../../util/StringFilter";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { SecurityOperationsCenterListRelationFilter } from "../../securityOperationsCenter/base/SecurityOperationsCenterListRelationFilter";
import { VirtualDesktopListRelationFilter } from "../../virtualDesktop/base/VirtualDesktopListRelationFilter";

@InputType()
class VirtualNetworkWhereInput {
  @ApiProperty({
    required: false,
    type: JsonFilter,
  })
  @Type(() => JsonFilter)
  @IsOptional()
  @Field(() => JsonFilter, {
    nullable: true,
  })
  addressSpace?: JsonFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  name?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  region?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: () => SecurityOperationsCenterListRelationFilter,
  })
  @ValidateNested()
  @Type(() => SecurityOperationsCenterListRelationFilter)
  @IsOptional()
  @Field(() => SecurityOperationsCenterListRelationFilter, {
    nullable: true,
  })
  securityOperationsCenters?: SecurityOperationsCenterListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => VirtualDesktopListRelationFilter,
  })
  @ValidateNested()
  @Type(() => VirtualDesktopListRelationFilter)
  @IsOptional()
  @Field(() => VirtualDesktopListRelationFilter, {
    nullable: true,
  })
  virtualDesktops?: VirtualDesktopListRelationFilter;
}

export { VirtualNetworkWhereInput as VirtualNetworkWhereInput };
